WITH RESULT AS
(SELECT A, B, C, D FROM TABLE1),
RESULT2 AS 
(SELECT E, F, G, H FROM RESULT),
RESULT3 AS 
(SELECT I, J, K, L FROM RESULT2)
SELECT A, E, J FROM TABLE1 JOIN TABLE2 ON TABLE1.A = TABLE2.F LEFT JOIN TABLE3 ON TABLE2.H = TABLE3.L FROM RESULT3